### ISSUE TITLE
Search bar are visible on new tab

### ISSUE THREAD

**Issue by Naezr** [Tagggar/Firefox-Alpha#2] opened 2023-11-08 15:26 UTC
![image](https://github.com/Tagggar/Firefox-Alpha/assets/95460152/667faec5-d487-4e43-bb15-2a7cc9a65f82) 
![image](https://github.com/Tagggar/Firefox-Alpha/assets/95460152/e4d25aec-7c93-46fb-8054-5f1a353c38c8)

The search bar is visible behind the buttons. This happens only on new tabs. On web pages everything looks as it should.

**Comment by Tagggar** [comment] 2023-11-09 09:21
Hi, thanks for the feedback.

Did You disabled suggestions pop-ups and what Firefox version? 

### To disable search suggestions pop-up:

Type `about:config` in URL Bar and set: `browser.urlbar.maxRichResults` > `0`

**Comment by Tagggar** [comment] 2023-11-09 09:57
If you want to keep search suggestions pop-up and just hide that urlbar text - add this code to the end of `userChrome.css`:

```
/* Search Suggestions Fix*/
#urlbar-container #urlbar-input-container {
  opacity: 0;
}
.urlbarView {
  background-color: var(--lwt-accent-color); /* Pop-up background color (adaptive) */
  color: grey;                               /* Pop-up text color */
}
```

**Comment by Naezr** [comment] 2023-11-09 12:40
Yes, I turned off the suggestion popup, but that didn't help. But this code did: https://github.com/MrOtherGuy/firefox-csshacks/blob/master/chrome/bookmarks_toolbar_on_newtabs_only.css
However, it doesn't help all the way, it leaves an empty line. For some reason, if I enable the "show bookmarks always" setting, this bug disappears
I use Firefox 119.0.1 on Windows 10

**Comment by Tagggar** [comment] 2023-11-09 13:45
> Yes, I turned off the suggestion popup, but that didn't help. But this code did: https://github.com/MrOtherGuy/firefox-csshacks/blob/master/chrome/bookmarks_toolbar_on_newtabs_only.css

As I can see, that code modifies some native Firefox root parameters, such as --uc-bm-padding. The new values may affect the positioning of elements, so it's advisable to review and adjust your configuration accordingly.

**Comment by Tagggar** [comment] 2023-11-09 13:53
> search bar is visible behind the buttons

A similar issue was fixed in [Issue #1](https://github.com/Tagggar/Firefox-Alpha/issues/1#issuecomment-1793766243) – please check that for reference.

I can't reproduce the issue on my end.

**Comment by Naezr** [comment] 2023-11-09 14:05
Thanks, the solution from issue1 worked. I should have looked in there sooner.

**Comment by Tagggar** [comment] 2023-11-09 14:23
Glad to hear that! Closing the gate!

**Closed as completed by Tagggar** 2023-11-09 14:23 UTC
